### ISSUE TITLE
Syntax highlighting of attributes with <. .>

### ISSUE THREAD

**Issue by alexeyr** [micalevisk/cocosyntax-vscode#2]
From the Coco/R user manual:

> If attributes contain the
operators `'<'` or `'>'` or generic types like `List<T>` the attribute brackets must be
written as `<. ... .>`.

In this case attributes are highlighted incorrectly, e.g.

    show<.std::vector<int> &values.> = ...

only the `std::vector<int` part is highlighted as an attribute.

**Comment by micalevisk** [comment]
fixed _(I hope; I'm pretty new to VSC extensions)_ in `v1.1.4` Thank you!

![now](https://user-images.githubusercontent.com/13461315/125518873-7d4d8c05-4c0f-44b3-be63-b33e6caa1550.png)

![now](https://user-images.githubusercontent.com/13461315/125519478-a7aff240-46ea-4e7e-aad2-23e0f3b82b21.png)
